name: golangci-lint
on:
  push:
    paths:
      - '**.go'
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.50.0
          args: -c .golang-ci.yml -v --timeout=5m
        env:
          GO111MODULES: off